# coding: utf-8

"""
    Selling Partner API for Catalog Items

    The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.uploads_api import UploadsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUploadsApi(unittest.TestCase):
    """UploadsApi unit test stubs"""

    def setUp(self):
        self.api = api.uploads_api.UploadsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_upload_destination_for_resource(self):
        """Test case for create_upload_destination_for_resource

        """
        pass


if __name__ == '__main__':
    unittest.main()
