# coding: utf-8

"""
    Selling Partner API for Catalog Items

    The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import amazon_selling_partner_api
from amazon_selling_partner_api.api.feeds_api import FeedsApi  # noqa: E501
from amazon_selling_partner_api.rest import ApiException


class TestFeedsApi(unittest.TestCase):
    """FeedsApi unit test stubs"""

    def setUp(self):
        self.api = FeedsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_feed(self):
        """Test case for cancel_feed

        """
        pass

    def test_create_feed(self):
        """Test case for create_feed

        """
        pass

    def test_create_feed_document(self):
        """Test case for create_feed_document

        """
        pass

    def test_get_feed(self):
        """Test case for get_feed

        """
        pass

    def test_get_feed_document(self):
        """Test case for get_feed_document

        """
        pass

    def test_get_feeds(self):
        """Test case for get_feeds

        """
        pass


if __name__ == '__main__':
    unittest.main()
