# coding: utf-8

"""
    Selling Partner API for Catalog Items

    The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.sales_api import SalesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSalesApi(unittest.TestCase):
    """SalesApi unit test stubs"""

    def setUp(self):
        self.api = api.sales_api.SalesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_order_metrics(self):
        """Test case for get_order_metrics

        """
        pass


if __name__ == '__main__':
    unittest.main()
