# coding: utf-8

"""
    Selling Partner API for Catalog Items

    The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.fba_outbound_api import FbaOutboundApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFbaOutboundApi(unittest.TestCase):
    """FbaOutboundApi unit test stubs"""

    def setUp(self):
        self.api = api.fba_outbound_api.FbaOutboundApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_fulfillment_order(self):
        """Test case for cancel_fulfillment_order

        """
        pass

    def test_create_fulfillment_order(self):
        """Test case for create_fulfillment_order

        """
        pass

    def test_create_fulfillment_return(self):
        """Test case for create_fulfillment_return

        """
        pass

    def test_get_fulfillment_order(self):
        """Test case for get_fulfillment_order

        """
        pass

    def test_get_fulfillment_preview(self):
        """Test case for get_fulfillment_preview

        """
        pass

    def test_get_package_tracking_details(self):
        """Test case for get_package_tracking_details

        """
        pass

    def test_list_all_fulfillment_orders(self):
        """Test case for list_all_fulfillment_orders

        """
        pass

    def test_list_return_reason_codes(self):
        """Test case for list_return_reason_codes

        """
        pass

    def test_update_fulfillment_order(self):
        """Test case for update_fulfillment_order

        """
        pass


if __name__ == '__main__':
    unittest.main()
