# coding: utf-8

"""
    Selling Partner API for Catalog Items

    The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.catalog_api import CatalogApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCatalogApi(unittest.TestCase):
    """CatalogApi unit test stubs"""

    def setUp(self):
        self.api = api.catalog_api.CatalogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_catalog_item(self):
        """Test case for get_catalog_item

        """
        pass

    def test_list_catalog_categories(self):
        """Test case for list_catalog_categories

        """
        pass

    def test_list_catalog_items(self):
        """Test case for list_catalog_items

        """
        pass


if __name__ == '__main__':
    unittest.main()
