# coding: utf-8

"""
    Selling Partner API for Catalog Items

    The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import amazon_selling_partner_api
from amazon_selling_partner_api.api.service_api import ServiceApi  # noqa: E501
from amazon_selling_partner_api.rest import ApiException


class TestServiceApi(unittest.TestCase):
    """ServiceApi unit test stubs"""

    def setUp(self):
        self.api = ServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_appointment_for_service_job_by_service_job_id(self):
        """Test case for add_appointment_for_service_job_by_service_job_id

        """
        pass

    def test_cancel_service_job_by_service_job_id(self):
        """Test case for cancel_service_job_by_service_job_id

        """
        pass

    def test_complete_service_job_by_service_job_id(self):
        """Test case for complete_service_job_by_service_job_id

        """
        pass

    def test_get_service_job_by_service_job_id(self):
        """Test case for get_service_job_by_service_job_id

        """
        pass

    def test_get_service_jobs(self):
        """Test case for get_service_jobs

        """
        pass

    def test_reschedule_appointment_for_service_job_by_service_job_id(self):
        """Test case for reschedule_appointment_for_service_job_by_service_job_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
