# coding: utf-8

"""
    Selling Partner API for Catalog Items

    The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.merchant_fulfillment_api import MerchantFulfillmentApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMerchantFulfillmentApi(unittest.TestCase):
    """MerchantFulfillmentApi unit test stubs"""

    def setUp(self):
        self.api = api.merchant_fulfillment_api.MerchantFulfillmentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_shipment(self):
        """Test case for cancel_shipment

        """
        pass

    def test_cancel_shipment_old(self):
        """Test case for cancel_shipment_old

        """
        pass

    def test_create_shipment(self):
        """Test case for create_shipment

        """
        pass

    def test_get_additional_seller_inputs(self):
        """Test case for get_additional_seller_inputs

        """
        pass

    def test_get_additional_seller_inputs_old(self):
        """Test case for get_additional_seller_inputs_old

        """
        pass

    def test_get_eligible_shipment_services(self):
        """Test case for get_eligible_shipment_services

        """
        pass

    def test_get_eligible_shipment_services_old(self):
        """Test case for get_eligible_shipment_services_old

        """
        pass

    def test_get_shipment(self):
        """Test case for get_shipment

        """
        pass


if __name__ == '__main__':
    unittest.main()
