# coding: utf-8

"""
    Selling Partner API for Catalog Items

    The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import amazon_selling_partner_api
from amazon_selling_partner_api.api.notifications_api import NotificationsApi  # noqa: E501
from amazon_selling_partner_api.rest import ApiException


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self):
        self.api = NotificationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_destination(self):
        """Test case for create_destination

        """
        pass

    def test_create_subscription(self):
        """Test case for create_subscription

        """
        pass

    def test_delete_destination(self):
        """Test case for delete_destination

        """
        pass

    def test_delete_subscription_by_id(self):
        """Test case for delete_subscription_by_id

        """
        pass

    def test_get_destination(self):
        """Test case for get_destination

        """
        pass

    def test_get_destinations(self):
        """Test case for get_destinations

        """
        pass

    def test_get_subscription(self):
        """Test case for get_subscription

        """
        pass

    def test_get_subscription_by_id(self):
        """Test case for get_subscription_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
