# coding: utf-8

"""
    Selling Partner API for Catalog Items

    The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import amazon_selling_partner_api
from amazon_selling_partner_api.api.default_api import DefaultApi  # noqa: E501
from amazon_selling_partner_api.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_financial_event_groups(self):
        """Test case for list_financial_event_groups

        """
        pass

    def test_list_financial_events(self):
        """Test case for list_financial_events

        """
        pass

    def test_list_financial_events_by_group_id(self):
        """Test case for list_financial_events_by_group_id

        """
        pass

    def test_list_financial_events_by_order_id(self):
        """Test case for list_financial_events_by_order_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
